app:
  name: "Closi"

log:
  level: "debug"
  format: "console"

http:
  host: "127.0.0.1"
  port: 8080
  read_timeout: 10s
  write_timeout: 30s
  idle_timeout: 60s

mongo:
  uri: "mongodb+srv://xxehwuq:hEWl8aQa1LSNCk3J@closi.pe58k.mongodb.net"
  database: "Closi"

auth:
  password:
    salt: "q2lU1IzVZc3V6ehzsolRA0tZU0gSftbC30KJNlZYJ8jERSCw5R442pguuTSiDUM"

  tokens:
    access_token:
      signing_key: "m0Tvu66drOHfNX7B8cEgtHePBFTjNTjOgsceOrX8MF57AjvkS7MBE6Lw26bG4OD"
      ttl: 15m
    refresh_token:
      length: 32
      ttl: 30d
