app:
  name: "Closi"

log:
  level: "debug"
  format: "console"

http:
  host: "127.0.0.1"
  port: 8080
  read_timeout: 10s
  write_timeout: 30s
  idle_timeout: 60s

mongo:
  uri: "mongodb+srv://xxehwuq:hEWl8aQa1LSNCk3J@closi.pe58k.mongodb.net"
  database: "Closi"