// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Closi-App/backend/internal/config"
	"github.com/Closi-App/backend/internal/logger"
	"github.com/Closi-App/backend/internal/repository"
	"github.com/Closi-App/backend/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config) (service.UserService, func(), error) {
	loggerLogger := logger.NewZerolog(configConfig)
	serviceService := service.NewService(loggerLogger)
	database := repository.NewDB(configConfig, loggerLogger)
	repositoryRepository := repository.NewRepository(loggerLogger, database)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	return userService, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService)
