// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Closi-App/backend/internal/config"
	"github.com/Closi-App/backend/internal/logger"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config) (logger.Logger, func(), error) {
	loggerLogger := logger.NewZerolog(configConfig)
	return loggerLogger, func() {
	}, nil
}
